/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_fred_lua_common_lua_LuaJavaBridge */

#ifndef _Included_net_fred_lua_common_lua_LuaJavaBridge
#define _Included_net_fred_lua_common_lua_LuaJavaBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_fred_lua_common_lua_LuaJavaBridge
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_fred_lua_common_lua_LuaJavaBridge_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_fred_lua_common_lua_LuaJavaBridge
 * Method:    nativeNewState
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_fred_lua_common_lua_LuaJavaBridge_nativeNewState
  (JNIEnv *, jobject);

/*
 * Class:     net_fred_lua_common_lua_LuaJavaBridge
 * Method:    nativeGetGlobal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_fred_lua_common_lua_LuaJavaBridge_nativeGetGlobal
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     net_fred_lua_common_lua_LuaJavaBridge
 * Method:    nativePushNumber
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_fred_lua_common_lua_LuaJavaBridge_nativePushNumber
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_fred_lua_common_lua_LuaJavaBridge
 * Method:    nativeToInteger
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_fred_lua_common_lua_LuaJavaBridge_nativeToInteger
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_fred_lua_common_lua_LuaJavaBridge
 * Method:    nativeCall
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_net_fred_lua_common_lua_LuaJavaBridge_nativeCall
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     net_fred_lua_common_lua_LuaJavaBridge
 * Method:    nativePop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_fred_lua_common_lua_LuaJavaBridge_nativePop
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_fred_lua_common_lua_LuaJavaBridge
 * Method:    nativeOpenlibs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_fred_lua_common_lua_LuaJavaBridge_nativeOpenlibs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_fred_lua_common_lua_LuaJavaBridge
 * Method:    nativeDofile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_fred_lua_common_lua_LuaJavaBridge_nativeDofile
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
